name: Build and Push Docker Image

on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./jupyter
          push: true
          tags: |
            wongsingfo/jupyter:latest
            wongsingfo/jupyter:amd64
            wongsingfo/jupyter:arm64
          platforms: linux/amd64,linux/arm64
